### PR TITLE
License everything under MIT/Apache 2.0 dual license.

### LINKED ISSUE #4: License
There should be an explicit license on all content in this repo and the challenges/responses linked to it to make it clear under what circumstances can it be re-used and distributed.

Simply copying the conditions from https://github.com/zcash/mpc#license would be fine IMO.

### PR DESCRIPTION
**Pull request by ebfull**
Closes #4 

# Contributor checkoff

To agree to relicensing, comment with :

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
```

- [x] @ebfull
- [x] @jasondavies 
- [x] @Souptacular 
- [x] @amiller 
- [x] @jtobin
- [x] @MDrollette

### CODE REVIEW

**Comment by ebfull** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Souptacular** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jasondavies** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by MDrollette** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jtobin** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by amiller** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ebfull** [comment]
Thanks for doing that so quick everyone. You rock!

**Pull request merged**
