### PR TITLE
lists.z.cash.foundation has moved to lists.zfnd.org

### PR DESCRIPTION
**Pull request by daira**
Note that the instance in `0088/beacon.txt.asc` has not been changed since that would invalidate the signature.

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Review by r3ld3v — APPROVED** [review]
utACK

**Review by sellout — APPROVED** [review]
Looks good.

Should we suggest that ZF point the old domain at a redirecting server? Or do they not control the domain any more?

**Comment by mpguerra** [comment]
What exactly is required from the Foundation here? A redirect from "lists.z.cash.foundation" to "lists.zfnd.org"? Or an approval on this PR? or something else? :)

**Review by mpguerra — APPROVED** [review]

**Comment by teor2345** [comment]
Mergify isn't on this repository, so we need to merge PRs as well as approving them.

**Pull request merged**
