### PR TITLE
Attestation 72

### PR DESCRIPTION
**Pull request by SleepingShell**
Adding a folder containing info for attestation 72.

### CODE REVIEW

**Comment by ebfull** [comment]
Can you fix merge conflicts? :) Thanks!

**Comment by jasondavies** [comment]
Should be no. 74 as we hadn't added the previous participants (72 & 73) yet.

**Comment by SleepingShell** [comment]
Sorry about that, should be fixed now

**Comment by jasondavies** [comment]
Thanks!

**Pull request closed without merging**
