### PR TITLE
Zaki Manian

### PR DESCRIPTION
**Pull request by zmanian**
Documenting my contribution

### CODE REVIEW

**Review by odeke-em — COMMENTED** [review]
@zmanian, just a drive-by comment: is the nomenclature of the directories padded with zeroes `0020` as your current directory for example https://github.com/ZcashFoundation/powersoftau-attestations/blob/03a6d3dc088a231906571fcece14acf285b1209f/0020/README.md or did you mean to make a new directory `20`?

**Comment by ebfull** [comment]
Can you rebase this? Sorry I didn't notice the PR beforehand.

**Comment by zmanian** [comment]
rebased

**Comment by ebfull** [comment]
@odeke-em Yeah, padding until 4 digits is what I've been doing since the start. :)

**Comment by ebfull** [comment]
Thanks @zmanian! :)

**Pull request merged**
